version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env
       
       
    prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"


      ##create a csvserver.env
      CSVSERVER_BORDER=Orange



      
